server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.101:1111 #配置Nacos地址 - 1111是集群nginx的虚拟地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

