server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: 192.168.100.101:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.100.101:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.100.101:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow



    #忽略虚拟机的虚拟网卡
    inetutils:
      ignored-interfaces:
        - VMware Network Adapter VMnet1
        - VMware Network Adapter VMnet8

management:
  endpoints:
    web:
      exposure:
        include: '*'




